name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.work
          cache-dependency-path: "**/*.sum"

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Run go test
        run: |
          make test

  goimports:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.work
          cache-dependency-path: "**/*.sum"

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: Run goimports
        run: |
          make format
          git -c color.ui=always diff --exit-code --stat

  go-generate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.work
          cache-dependency-path: "**/*.sum"

      - name: Run go generate
        run: |
          make generate
          git -c color.ui=always diff --exit-code --stat
